[0m11:46:42.224917 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7597df643b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7597df643f90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7597df642450>]}


============================== 11:46:42.228368 | fde39e8f-799a-4962-9354-11ca11d745a3 ==============================
[0m11:46:42.228368 [info ] [MainThread]: Running with dbt=1.9.0-b4
[0m11:46:42.228969 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/sukuna/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:46:50.328523 [debug] [MainThread]: Starter project path: /home/sukuna/miniconda3/envs/data/lib/python3.11/site-packages/dbt/include/starter_project
[0m11:46:50.343346 [info ] [MainThread]: 
Your new dbt project "etl_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:46:50.344857 [info ] [MainThread]: Setting up your profile.
[0m11:47:20.063874 [info ] [MainThread]: Profile etl_pipeline written to /home/sukuna/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m11:47:20.067942 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 37.89836, "process_user_time": 2.460053, "process_kernel_time": 0.436785, "process_mem_max_rss": "91684", "process_in_blocks": "92480", "process_out_blocks": "80"}
[0m11:47:20.069989 [debug] [MainThread]: Command `dbt init` succeeded at 11:47:20.069606 after 37.90 seconds
[0m11:47:20.071398 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7597df6ac350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7597e2f1e310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7597e2e61090>]}
[0m11:47:20.073477 [debug] [MainThread]: Flushing usage events
[0m11:47:21.294722 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:38:20.202112 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78df8abb9a50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78df8abb9990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78df8abbbd50>]}


============================== 16:38:20.205994 | abdfd00b-8837-43cd-9316-efd273f5c599 ==============================
[0m16:38:20.205994 [info ] [MainThread]: Running with dbt=1.9.0-b4
[0m16:38:20.206875 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/sukuna/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:38:20.207632 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/sukuna/Documents/PROJECTS/ETL_Pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:38:20.209543 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.12363959, "process_user_time": 2.72986, "process_kernel_time": 0.493602, "process_mem_max_rss": "87156", "process_in_blocks": "65928", "process_out_blocks": "16", "command_success": false}
[0m16:38:20.210323 [debug] [MainThread]: Command `dbt run` failed at 16:38:20.210169 after 0.12 seconds
[0m16:38:20.210870 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78df8ac21810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78df8e416750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78df8e4b9950>]}
[0m16:38:20.211428 [debug] [MainThread]: Flushing usage events
[0m16:38:21.518802 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:07:11.572359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7052acc75f90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7052ad153f50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7052acc6ec50>]}


============================== 19:07:11.575834 | fa1444c3-5d19-47af-979e-a4d2525e6ff9 ==============================
[0m19:07:11.575834 [info ] [MainThread]: Running with dbt=1.9.0-b4
[0m19:07:11.576331 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/sukuna/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt test', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m19:07:11.576815 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/sukuna/Documents/PROJECTS/ETL_Pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:07:11.577558 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.08132595, "process_user_time": 0.91232, "process_kernel_time": 0.116657, "process_mem_max_rss": "87716", "process_in_blocks": "400", "process_out_blocks": "8", "command_success": false}
[0m19:07:11.578039 [debug] [MainThread]: Command `dbt test` failed at 19:07:11.577949 after 0.08 seconds
[0m19:07:11.578422 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7052b051a7d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7052acc74290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7052b05bda90>]}
[0m19:07:11.578803 [debug] [MainThread]: Flushing usage events
[0m19:07:12.893350 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:20:49.656032 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7674887c3ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7674882debd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7674882dee50>]}


============================== 13:20:49.662467 | 900810f1-c873-45a0-ab9f-898e53ab6348 ==============================
[0m13:20:49.662467 [info ] [MainThread]: Running with dbt=1.9.0-b4
[0m13:20:49.662929 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/sukuna/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:20:49.663385 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/sukuna/Documents/PROJECTS/ETL_Pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:20:49.664543 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.0496662, "process_user_time": 0.932458, "process_kernel_time": 0.091946, "process_mem_max_rss": "87876", "process_in_blocks": "8", "process_out_blocks": "8", "command_success": false}
[0m13:20:49.665152 [debug] [MainThread]: Command `dbt run` failed at 13:20:49.665017 after 0.05 seconds
[0m13:20:49.665761 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76748bc1a310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76748834f910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x76748834f850>]}
[0m13:20:49.666645 [debug] [MainThread]: Flushing usage events
[0m13:20:50.963455 [debug] [MainThread]: An error was encountered while trying to flush usage events
