[2024-11-18T12:38:21.398+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T12:38:21.407+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_dag.dbt_test scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T12:38:21.417+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_dag.dbt_test scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T12:38:21.418+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-18T12:38:21.440+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_test> on 2024-11-17 00:00:00+00:00
[2024-11-18T12:38:21.447+0000] {standard_task_runner.py:72} INFO - Started process 186 to run task
[2024-11-18T12:38:21.451+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline_dag', 'dbt_test', 'scheduled__2024-11-17T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp5zu3ggnq']
[2024-11-18T12:38:21.453+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask dbt_test
[2024-11-18T12:38:21.517+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_dag.dbt_test scheduled__2024-11-17T00:00:00+00:00 [running]> on host 945969587f65
[2024-11-18T12:38:21.832+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline_dag' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T00:00:00+00:00'
[2024-11-18T12:38:21.834+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T12:38:21.910+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-18T12:38:21.913+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/etl_pipeline && dbt test --profiles-dir /opt/airflow/etl_pipeline']
[2024-11-18T12:38:21.937+0000] {subprocess.py:99} INFO - Output:
[2024-11-18T12:38:24.062+0000] {subprocess.py:106} INFO - [0m12:38:24  Running with dbt=1.8.8
[2024-11-18T12:38:24.589+0000] {subprocess.py:106} INFO - [0m12:38:24  Registered adapter: postgres=1.8.2
[2024-11-18T12:38:24.882+0000] {subprocess.py:106} INFO - [0m12:38:24  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-11-18T12:38:24.882+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2024-11-18T12:38:24.883+0000] {subprocess.py:106} INFO - - models.etl_pipeline.production
[2024-11-18T12:38:25.068+0000] {subprocess.py:106} INFO - [0m12:38:25  Found 6 models, 26 data tests, 2 sources, 539 macros
[2024-11-18T12:38:25.072+0000] {subprocess.py:106} INFO - [0m12:38:25
[2024-11-18T12:38:25.247+0000] {subprocess.py:106} INFO - [0m12:38:25  Concurrency: 1 threads (target='dev')
[2024-11-18T12:38:25.248+0000] {subprocess.py:106} INFO - [0m12:38:25
[2024-11-18T12:38:25.259+0000] {subprocess.py:106} INFO - [0m12:38:25  1 of 26 START test dbt_utils_expression_is_true_fact_revenue_minutes_to_service___0  [RUN]
[2024-11-18T12:38:25.443+0000] {subprocess.py:106} INFO - [0m12:38:25  1 of 26 PASS dbt_utils_expression_is_true_fact_revenue_minutes_to_service___0 .. [[32mPASS[0m in 0.18s]
[2024-11-18T12:38:25.452+0000] {subprocess.py:106} INFO - [0m12:38:25  2 of 26 START test dbt_utils_expression_is_true_fact_revenue_number_of_patient_visits___1  [RUN]
[2024-11-18T12:38:25.555+0000] {subprocess.py:106} INFO - [0m12:38:25  2 of 26 PASS dbt_utils_expression_is_true_fact_revenue_number_of_patient_visits___1  [[32mPASS[0m in 0.10s]
[2024-11-18T12:38:25.562+0000] {subprocess.py:106} INFO - [0m12:38:25  3 of 26 START test dbt_utils_expression_is_true_fact_revenue_revenue___0 ....... [RUN]
[2024-11-18T12:38:25.667+0000] {subprocess.py:106} INFO - [0m12:38:25  3 of 26 PASS dbt_utils_expression_is_true_fact_revenue_revenue___0 ............. [[32mPASS[0m in 0.10s]
[2024-11-18T12:38:25.677+0000] {subprocess.py:106} INFO - [0m12:38:25  4 of 26 START test not_null_dim_doctors_department ............................. [RUN]
[2024-11-18T12:38:25.791+0000] {subprocess.py:106} INFO - [0m12:38:25  4 of 26 PASS not_null_dim_doctors_department ................................... [[32mPASS[0m in 0.11s]
[2024-11-18T12:38:25.801+0000] {subprocess.py:106} INFO - [0m12:38:25  5 of 26 START test not_null_dim_doctors_doctor ................................. [RUN]
[2024-11-18T12:38:25.923+0000] {subprocess.py:106} INFO - [0m12:38:25  5 of 26 PASS not_null_dim_doctors_doctor ....................................... [[32mPASS[0m in 0.12s]
[2024-11-18T12:38:25.933+0000] {subprocess.py:106} INFO - [0m12:38:25  6 of 26 START test not_null_dim_patients_patient_id ............................ [RUN]
[2024-11-18T12:38:26.017+0000] {subprocess.py:106} INFO - [0m12:38:26  6 of 26 PASS not_null_dim_patients_patient_id .................................. [[32mPASS[0m in 0.08s]
[2024-11-18T12:38:26.026+0000] {subprocess.py:106} INFO - [0m12:38:26  7 of 26 START test not_null_dim_patients_patient_name .......................... [RUN]
[2024-11-18T12:38:26.109+0000] {subprocess.py:106} INFO - [0m12:38:26  7 of 26 PASS not_null_dim_patients_patient_name ................................ [[32mPASS[0m in 0.08s]
[2024-11-18T12:38:26.114+0000] {subprocess.py:106} INFO - [0m12:38:26  8 of 26 START test not_null_fact_revenue_branch_id ............................. [RUN]
[2024-11-18T12:38:26.171+0000] {subprocess.py:106} INFO - [0m12:38:26  8 of 26 PASS not_null_fact_revenue_branch_id ................................... [[32mPASS[0m in 0.06s]
[2024-11-18T12:38:26.175+0000] {subprocess.py:106} INFO - [0m12:38:26  9 of 26 START test not_null_fact_revenue_doctor_id ............................. [RUN]
[2024-11-18T12:38:26.252+0000] {subprocess.py:106} INFO - [0m12:38:26  9 of 26 PASS not_null_fact_revenue_doctor_id ................................... [[32mPASS[0m in 0.08s]
[2024-11-18T12:38:26.255+0000] {subprocess.py:106} INFO - [0m12:38:26  10 of 26 START test not_null_fact_revenue_minutes_to_service ................... [RUN]
[2024-11-18T12:38:26.292+0000] {subprocess.py:106} INFO - [0m12:38:26  10 of 26 PASS not_null_fact_revenue_minutes_to_service ......................... [[32mPASS[0m in 0.04s]
[2024-11-18T12:38:26.295+0000] {subprocess.py:106} INFO - [0m12:38:26  11 of 26 START test not_null_fact_revenue_number_of_patient_visits ............. [RUN]
[2024-11-18T12:38:26.326+0000] {subprocess.py:106} INFO - [0m12:38:26  11 of 26 PASS not_null_fact_revenue_number_of_patient_visits ................... [[32mPASS[0m in 0.03s]
[2024-11-18T12:38:26.329+0000] {subprocess.py:106} INFO - [0m12:38:26  12 of 26 START test not_null_fact_revenue_patient_id ........................... [RUN]
[2024-11-18T12:38:26.409+0000] {subprocess.py:106} INFO - [0m12:38:26  12 of 26 PASS not_null_fact_revenue_patient_id ................................. [[32mPASS[0m in 0.08s]
[2024-11-18T12:38:26.416+0000] {subprocess.py:106} INFO - [0m12:38:26  13 of 26 START test not_null_fact_revenue_revenue .............................. [RUN]
[2024-11-18T12:38:26.497+0000] {subprocess.py:106} INFO - [0m12:38:26  13 of 26 PASS not_null_fact_revenue_revenue .................................... [[32mPASS[0m in 0.08s]
[2024-11-18T12:38:26.504+0000] {subprocess.py:106} INFO - [0m12:38:26  14 of 26 START test not_null_fact_revenue_risk_id .............................. [RUN]
[2024-11-18T12:38:26.587+0000] {subprocess.py:106} INFO - [0m12:38:26  14 of 26 PASS not_null_fact_revenue_risk_id .................................... [[32mPASS[0m in 0.08s]
[2024-11-18T12:38:26.593+0000] {subprocess.py:106} INFO - [0m12:38:26  15 of 26 START test not_null_fact_revenue_row_id ............................... [RUN]
[2024-11-18T12:38:26.669+0000] {subprocess.py:106} INFO - [0m12:38:26  15 of 26 PASS not_null_fact_revenue_row_id ..................................... [[32mPASS[0m in 0.07s]
[2024-11-18T12:38:26.676+0000] {subprocess.py:106} INFO - [0m12:38:26  16 of 26 START test relationships_fact_revenue_branch_id__branch_id__ref_dim_branches_  [RUN]
[2024-11-18T12:38:26.775+0000] {subprocess.py:106} INFO - [0m12:38:26  16 of 26 PASS relationships_fact_revenue_branch_id__branch_id__ref_dim_branches_  [[32mPASS[0m in 0.10s]
[2024-11-18T12:38:26.780+0000] {subprocess.py:106} INFO - [0m12:38:26  17 of 26 START test relationships_fact_revenue_doctor_id__doctor_id__ref_dim_doctors_  [RUN]
[2024-11-18T12:38:26.868+0000] {subprocess.py:106} INFO - [0m12:38:26  17 of 26 FAIL 6334 relationships_fact_revenue_doctor_id__doctor_id__ref_dim_doctors_  [[31mFAIL 6334[0m in 0.08s]
[2024-11-18T12:38:26.874+0000] {subprocess.py:106} INFO - [0m12:38:26  18 of 26 START test relationships_fact_revenue_patient_id__patient_id__ref_dim_patients_  [RUN]
[2024-11-18T12:38:26.979+0000] {subprocess.py:106} INFO - [0m12:38:26  18 of 26 PASS relationships_fact_revenue_patient_id__patient_id__ref_dim_patients_  [[32mPASS[0m in 0.10s]
[2024-11-18T12:38:26.985+0000] {subprocess.py:106} INFO - [0m12:38:26  19 of 26 START test relationships_fact_revenue_risk_id__risk_id__ref_dim_risk_ . [RUN]
[2024-11-18T12:38:27.066+0000] {subprocess.py:106} INFO - [0m12:38:27  19 of 26 PASS relationships_fact_revenue_risk_id__risk_id__ref_dim_risk_ ....... [[32mPASS[0m in 0.08s]
[2024-11-18T12:38:27.072+0000] {subprocess.py:106} INFO - [0m12:38:27  20 of 26 START test source_not_null_staging_data_staging_patient_visits_doctor . [RUN]
[2024-11-18T12:38:27.244+0000] {subprocess.py:106} INFO - [0m12:38:27  20 of 26 PASS source_not_null_staging_data_staging_patient_visits_doctor ....... [[32mPASS[0m in 0.17s]
[2024-11-18T12:38:27.250+0000] {subprocess.py:106} INFO - [0m12:38:27  21 of 26 START test source_not_null_staging_data_staging_patient_visits_patient_id  [RUN]
[2024-11-18T12:38:27.328+0000] {subprocess.py:106} INFO - [0m12:38:27  21 of 26 PASS source_not_null_staging_data_staging_patient_visits_patient_id ... [[32mPASS[0m in 0.08s]
[2024-11-18T12:38:27.334+0000] {subprocess.py:106} INFO - [0m12:38:27  22 of 26 START test source_not_null_staging_data_staging_patient_visits_row_id . [RUN]
[2024-11-18T12:38:27.405+0000] {subprocess.py:106} INFO - [0m12:38:27  22 of 26 PASS source_not_null_staging_data_staging_patient_visits_row_id ....... [[32mPASS[0m in 0.07s]
[2024-11-18T12:38:27.411+0000] {subprocess.py:106} INFO - [0m12:38:27  23 of 26 START test source_not_null_trans_staging_patient_visits_patient_id .... [RUN]
[2024-11-18T12:38:27.480+0000] {subprocess.py:106} INFO - [0m12:38:27  23 of 26 PASS source_not_null_trans_staging_patient_visits_patient_id .......... [[32mPASS[0m in 0.07s]
[2024-11-18T12:38:27.485+0000] {subprocess.py:106} INFO - [0m12:38:27  24 of 26 START test source_unique_staging_data_staging_patient_visits_row_id ... [RUN]
[2024-11-18T12:38:27.570+0000] {subprocess.py:106} INFO - [0m12:38:27  24 of 26 PASS source_unique_staging_data_staging_patient_visits_row_id ......... [[32mPASS[0m in 0.08s]
[2024-11-18T12:38:27.576+0000] {subprocess.py:106} INFO - [0m12:38:27  25 of 26 START test unique_dim_patients_patient_id ............................. [RUN]
[2024-11-18T12:38:27.646+0000] {subprocess.py:106} INFO - [0m12:38:27  25 of 26 PASS unique_dim_patients_patient_id ................................... [[32mPASS[0m in 0.07s]
[2024-11-18T12:38:27.652+0000] {subprocess.py:106} INFO - [0m12:38:27  26 of 26 START test unique_fact_revenue_row_id ................................. [RUN]
[2024-11-18T12:38:27.736+0000] {subprocess.py:106} INFO - [0m12:38:27  26 of 26 PASS unique_fact_revenue_row_id ....................................... [[32mPASS[0m in 0.08s]
[2024-11-18T12:38:27.788+0000] {subprocess.py:106} INFO - [0m12:38:27
[2024-11-18T12:38:27.789+0000] {subprocess.py:106} INFO - [0m12:38:27  Finished running 26 data tests in 0 hours 0 minutes and 2.71 seconds (2.71s).
[2024-11-18T12:38:27.946+0000] {subprocess.py:106} INFO - [0m12:38:27
[2024-11-18T12:38:27.947+0000] {subprocess.py:106} INFO - [0m12:38:27  [31mCompleted with 1 error and 0 warnings:[0m
[2024-11-18T12:38:27.948+0000] {subprocess.py:106} INFO - [0m12:38:27
[2024-11-18T12:38:27.950+0000] {subprocess.py:106} INFO - [0m12:38:27  [31mFailure in test relationships_fact_revenue_doctor_id__doctor_id__ref_dim_doctors_ (models/transformation/schema.yml)[0m
[2024-11-18T12:38:27.951+0000] {subprocess.py:106} INFO - [0m12:38:27    Got 6334 results, configured to fail if != 0
[2024-11-18T12:38:27.952+0000] {subprocess.py:106} INFO - [0m12:38:27
[2024-11-18T12:38:27.953+0000] {subprocess.py:106} INFO - [0m12:38:27    compiled code at target/compiled/etl_pipeline/models/transformation/schema.yml/relationships_fact_revenue_8e6b53c87420f4a42087e24ffb6d0d96.sql
[2024-11-18T12:38:27.954+0000] {subprocess.py:106} INFO - [0m12:38:27
[2024-11-18T12:38:27.956+0000] {subprocess.py:106} INFO - [0m12:38:27  Done. PASS=25 WARN=0 ERROR=1 SKIP=0 TOTAL=26
[2024-11-18T12:38:29.502+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2024-11-18T12:38:29.508+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-18T12:38:29.520+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline_dag, task_id=dbt_test, run_id=scheduled__2024-11-17T00:00:00+00:00, execution_date=20241117T000000, start_date=20241118T123821, end_date=20241118T123829
[2024-11-18T12:38:29.535+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T12:38:29.535+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 186)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-18T12:38:29.566+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-18T12:38:29.581+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T12:38:29.592+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
